### ISSUE TITLE
How to run in iOS?

### ISSUE THREAD

**Issue by bordline23** [stormlion227/ImageCropper.Forms#4]
Hi,

I created a new project and installed version 0.1.4 via nuget, but I'm getting these errors when building the iOS project. I tried building it using VS2017 connecting to mac and also building it using VS for Mac.  Am I missing something?

`5>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(786,3): error : Native linking failed, undefined Objective-C class: TOCropView. The symbol '_OBJC_CLASS_$_TOCropView' could not be found in any of the libraries or frameworks linked with your application.
5>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(786,3): error : Native linking failed, undefined Objective-C class: TOCropViewControllerTransitioning. The symbol '_OBJC_CLASS_$_TOCropViewControllerTransitioning' could not be found in any of the libraries or frameworks linked with your application.
5>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(786,3): error : Native linking failed, undefined Objective-C class: TOCropScrollView. The symbol '_OBJC_CLASS_$_TOCropScrollView' could not be found in any of the libraries or frameworks linked with your application.
5>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(786,3): error : Native linking failed, undefined Objective-C class: TOCroppedImageAttributes. The symbol '_OBJC_CLASS_$_TOCroppedImageAttributes' could not be found in any of the libraries or frameworks linked with your application.
5>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(786,3): error : Native linking failed, undefined Objective-C class: TOCropToolbar. The symbol '_OBJC_CLASS_$_TOCropToolbar' could not be found in any of the libraries or frameworks linked with your application.
5>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(786,3): error : Native linking failed, undefined Objective-C class: TOCropOverlayView. The symbol '_OBJC_CLASS_$_TOCropOverlayView' could not be found in any of the libraries or frameworks linked with your application.
5>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(786,3): error : Native linking failed, undefined Objective-C class: TOCropViewController. The symbol '_OBJC_CLASS_$_TOCropViewController' could not be found in any of the libraries or frameworks linked with your application.
5>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(786,3): error : Native linking failed, undefined Objective-C class: TOActivityCroppedImageProvider. The symbol '_OBJC_CLASS_$_TOActivityCroppedImageProvider' could not be found in any of the libraries or frameworks linked with your application.
5>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(786,3): error : Native linking failed. Please review the build log.`

Thanks for your help.

**Comment by Falconiere** [comment]
+1

**Comment by rasmusbjoernrasmussen** [comment]
I assume you are running on Simulator?

**Comment by rasmusbjoernrasmussen** [comment]
PR #7 created - implementing the Protocol Attribute to try to resolve this issue

**Comment by shreyans-wakekar** [comment]
Getting the same issue. i'm using version 0.1.5.
Need help.

**Comment by LynoDesu** [comment]
Also getting this issue in iOS:
![tocroperror](https://user-images.githubusercontent.com/17926055/42038105-0aaa7a5c-7ae2-11e8-8a80-83c8c3e91278.png)

**Comment by stormlion227** [comment]
It doesn't work with iPhone simulator.
It can run on real-device.
![2018-06-28_15h58_14](https://user-images.githubusercontent.com/24723104/42038836-32e9141a-7aec-11e8-85c1-10768343f781.png)

**Comment by LynoDesu** [comment]
Is there a reason for this? What's required to add simulator support?

**Comment by stormlion227** [comment]
I used this library.
https://github.com/TimOliver/TOCropViewController
It doesn't work with simulator.

**Comment by LynoDesu** [comment]
I've just cloned that git project and it works just fine in the  simulator:
<img width="382" alt="screen shot 2018-06-28 at 15 18 54" src="https://user-images.githubusercontent.com/17926055/42040083-c2f0dd6e-7ae6-11e8-96e5-c0c0f68a0a28.png">

**Comment by stormlion227** [comment]
Ok. When I have free time, I'll add simulator feature.

**Comment by stormlion227** [comment]
I've fixed iphonesimulator issue now (version 0.1.6)
